In [ ]:
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Feature Engineering/adult.csv')
data.head()

# UNTUK DATA YG BINARY

## Cara 1

In [4]:
data["gender"] = data["gender"].apply(lambda val: 
                                      1 if val == "Female" else 0) # Beri label 1 jika F dan 0 lainnya

data.head()

   age  workclass  fnlwgt  ... hours-per-week  native-country income
0   25    Private  226802  ...             40   United-States  <=50K
1   38    Private   89814  ...             50   United-States  <=50K
2   28  Local-gov  336951  ...             40   United-States   >50K
3   44    Private  160323  ...             40   United-States   >50K
4   18          ?  103497  ...             30   United-States  <=50K

[5 rows x 15 columns]

## Cara 2

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["gender"] = le.fit_transform(data["gender"])
data.head()

   age  workclass  fnlwgt  ... hours-per-week  native-country income
0   25    Private  226802  ...             40   United-States  <=50K
1   38    Private   89814  ...             50   United-States  <=50K
2   28  Local-gov  336951  ...             40   United-States   >50K
3   44    Private  160323  ...             40   United-States   >50K
4   18          ?  103497  ...             30   United-States  <=50K

[5 rows x 15 columns]

# UNTUK DATA YANG LEBIH DARI 2 VARIABEL

In [5]:
variabel_dummies_marital_status = pd.get_dummies(data['marital-status'])
print(variabel_dummies_marital_status)

       Divorced  Married-AF-spouse  ...  Separated  Widowed
0             0                  0  ...          0        0
1             0                  0  ...          0        0
2             0                  0  ...          0        0
3             0                  0  ...          0        0
4             0                  0  ...          0        0
...         ...                ...  ...        ...      ...
48837         0                  0  ...          0        0
48838         0                  0  ...          0        0
48839         0                  0  ...          0        1
48840         0                  0  ...          0        0
48841         0                  0  ...          0        0

[48842 rows x 7 columns]